name: snap_diet
description: "Your meal’s story in a single snap."
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.8
  dotted_border: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  image: ^4.5.3
  image_picker: ^1.1.2
  intl: ^0.20.2
  path: ^1.9.0
  shared_preferences: ^2.5.3
  sizer: ^3.0.5
  smooth_page_indicator: ^1.2.1
  sqflite: ^2.4.1
  tflite_flutter: ^0.11.0
  toast: ^0.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.4

flutter_native_splash:
  color: "#10B981"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/