name: snap_diet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  image: ^4.5.3
  image_picker: ^1.1.2
  intl: ^0.20.2
  path: ^1.9.0
  shared_preferences: ^2.5.3
  sizer: ^3.0.5
  smooth_page_indicator: ^1.2.1
  sqflite: ^2.4.1
  tflite_flutter: ^0.11.0
  toast: ^0.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/
    - assets/models/aiy.tflite
    - assets/models/aiy_food_V1_calories_&_recipes.json
    - assets/models/mobile_food_segmenter_V1.tflite
