name: snap_diet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  image: ^4.5.3
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0

dev_dependencies:

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/models/
    - assets/models/aiy.tflite
    - assets/models/mobile_food_segmenter_V1.tflite
